[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
  conditions = {Not = [path = "/.netlify/functions/api/*"]}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Accept"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://*.commerce7.com https://*.commerce7cdn.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.commerce7.com https://*.commerce7cdn.com; style-src 'self' 'unsafe-inline' https://*.commerce7cdn.com https://fonts.googleapis.com; img-src 'self' data: https://*.commerce7cdn.com https://i.imgur.com; font-src 'self' https://*.commerce7cdn.com https://fonts.gstatic.com; connect-src 'self' https://*.commerce7.com https://*.commerce7cdn.com https://club-calculator.netlify.app; frame-ancestors 'none';"

[functions]
  node_bundler = "esbuild"

[functions.environment]
  C7_APP_ID = "club-test"
  C7_SECRET_KEY = "zPfLmVXA3Yg8ht0NWEs1RJxqCuiQob7TKpdlZB65wOeMcHFUnr49kyavGj2StEMn"
  C7_TENANT_ID = "milea-estate-vineyard"
  PICKUP_LOCATION_ID = "e75bfc54-009d-43db-8ed7-113158cce63e"

[dev]
  port = 8888
  targetPort = 3000
  framework = "create-react-app"
  environment = { C7_APP_ID = "club-test", C7_SECRET_KEY = "zPfLmVXA3Yg8ht0NWEs1RJxqCuiQob7TKpdlZB65wOeMcHFUnr49kyavGj2StEMn", C7_TENANT_ID = "milea-estate-vineyard", PICKUP_LOCATION_ID = "e75bfc54-009d-43db-8ed7-113158cce63e" } 